image: Visual Studio 2017
configuration: Release
platform: Any CPU

before_build:
- cmd: dotnet restore

build:
  project: container.sln
  parallel: true
  verbosity: minimal

before_test:
- choco install opencover.portable
- choco install codecov
  
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test" -filter:"+[Unity*]* -[*]*Resources"

after_test:
- codecov -f "results.xml" 

