image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - ps: $env:build_version = (Select-Xml -Path ".\package.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText
  - ps: Update-AppveyorBuild -Version "$env:build_version.$env:APPVEYOR_BUILD_NUMBER"

assembly_info: 
  patch: false 
  assembly_informational_version: "{version} $(GIT_HASH)"

dotnet_csproj:
  patch: false

before_build:
- cmd: dotnet restore -v=n

build:
  project: package.sln
  parallel: true
  verbosity: minimal

after_build:
- choco install opencover.portable
- choco install codecov
  
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --framework net46 --verbosity q"

after_test:
- codecov -f "results.xml" 

artifacts:
- path: '**\Unity.*.nupkg'
  name: 'Unity'
