# Build pipeline

trigger:
- v5.x
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  PackageOutputPath: '$(build.artifactstagingdirectory)\Package'

steps:
- task: PowerShell@2
  displayName: 'Version Info'
  inputs:
    targetType: 'inline'
    script: |
      $version = (Select-Xml -Path ".\Directory.Build.props" -XPath "/Project/PropertyGroup/Version" | Select-Object -ExpandProperty Node).InnerText
      $timestamp = git log -1 --pretty="format:%ct"
      Write-Host "Version: $version" 
      if ([regex]::IsMatch($Env:BUILD_SOURCEBRANCH, "^(refs\/tags\/v)")) { 
          Write-Host "Package Version: $($version)" 
      } Else { 
          Write-Host "Package Version:$($version)-$($timestamp)" 
          Write-Host "##vso[task.setvariable variable=VERSION_SUFFIX]-$($timestamp)" 
      }

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

#- task: CopyFiles@2
#  displayName: 'Copy Properties'
#  inputs:
#    Contents: 'Directory.Build.props'
#    TargetFolder: 'src'

#- task: PublishBuildArtifacts@1
#  displayName: 'Stage Source'
#  inputs:
#    PathtoPublish: 'src'
#    artifactName: 'Source'

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'
    vstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'
    verbosityRestore: 'Normal'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    searchFolder: '$(system.defaultworkingdirectory)\tests'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Binaries'
  inputs:
    PathtoPublish: 'src\bin\$(buildConfiguration)'
    artifactName: 'Binaries'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Package'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\Package'
    artifactName: 'Package'

#- task: NuGetCommand@2
#  displayName: 'Local Feed'
#  inputs:
#    command: 'push'
#    packagesToPush: '$(build.artifactstagingdirectory)\Package\*.$(PACKAGE_VERSION).nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'
#    allowPackageConflicts: true
