# Build pipeline

trigger:
- v5.x
- refs/tags/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Version Info'
  inputs:
    targetType: 'inline'
    script: |
      $version = (Select-Xml -Path ".\Directory.Build.props" -XPath "/Project/PropertyGroup/VersionBase" | Select-Object -ExpandProperty Node).InnerText
      $timestamp = git log -1 --pretty="format:%ct"
      Write-Host "Version: $version" 
      Write-Host "Time Stamp: $timestamp" 
      if ([regex]::IsMatch($Env:BUILD_SOURCEBRANCH, "^(refs\/tags\/v)")) { 
          Write-Host "Package Version: $($version)" 
          Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION]$($version)" 
      } Else { 
          Write-Host "Package Version:$($version)-$($timestamp)" 
          Write-Host "##vso[task.setvariable variable=PACKAGE_VERSION]$($version)-$($timestamp)" 
      }

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: CopyFiles@2
  displayName: 'Copy Properties'
  inputs:
    Contents: 'Directory.Build.props'
    TargetFolder: 'src'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Source'
  inputs:
    PathtoPublish: 'src'
    artifactName: 'Source'

- task: NuGetCommand@2
  displayName: 'Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    searchFolder: '$(system.defaultworkingdirectory)\test'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Binaries'
  inputs:
    PathtoPublish: 'src\bin\$(buildConfiguration)'
    artifactName: 'Binaries'

- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: 'src/*.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PACKAGE_VERSION'
    verbosityPack: 'Minimal'
    packDirectory: '$(Build.ArtifactStagingDirectory)\Package'

- task: PublishBuildArtifacts@1
  displayName: 'Stage Package'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)\Package'
    artifactName: 'Package'

#- task: NuGetCommand@2
#  displayName: 'Local Feed'
#  inputs:
#    command: 'push'
#    packagesToPush: '$(build.artifactstagingdirectory)\Package\*.$(PACKAGE_VERSION).nupkg'
#    nuGetFeedType: 'internal'
#    publishVstsFeed: '18a6243f-7dac-4c78-bb92-3af88cd8e255'
#    allowPackageConflicts: true
