name:  Continuous Deployment

on:
  push:
    branches:
      - 'release/**'    
      - 'prototype/**'    

permissions:
  packages: write

jobs:

  build:
    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'

    steps:
    - name: Checkout Container
      uses: actions/checkout@v3
      with:
        path: Container
        fetch-depth: 0

    - name: GitVersion
      run: | 
        choco install gitversion.portable -pre -y --no-progress
        gitversion /l console /output buildserver /config .github\gitversion.yml /targetpath Container

    # - name: Setup .NET Core SDK
    #   uses: actions/setup-dotnet@v3.0.3
    #   with:
    #     dotnet-version: '8.0'
        
    - name: Build
      env:
        VersionMajor: '${{ env.GitVersion_Major }}'
        VersionMinor: '${{ env.GitVersion_Minor }}'
        VersionPatch: '${{ env.GitVersion_Patch }}'
        Version: '${{ env.GitVersion_MajorMinorPatch }}'
        FileVersion: '${{ env.GitVersion_AssemblySemFileVer }}'
        PackageVersion: '${{ env.GitVersion_SemVer }}'
        AssemblyVersion: '${{ env.GitVersion_AssemblySemVer }}'
        InformationalVersion: '${{ env.GitVersion_InformationalVersion }}'
      run: | 
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ github.workspace }}\Container\package.sln

    - name: Test
      run: | 
        dotnet test --no-restore --no-build ${{ github.workspace }}\Container\package.sln

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github

    - name: Label Fixed Issues
      uses: gh-bot/fix-labeler@master        
      with:
        path: Container
