name:  Continuous Deployment

on:
  push:
    branches: [ develop ]
    # paths:
    #   - 'src/*'
    #   - 'test/*'

jobs:

  build:
    runs-on: windows-latest
    env:
      PackageOutputPath: '${{ github.workspace }}\package'
      containerProject:  '${{ github.workspace }}\Container\src\Unity.Container.csproj'

    steps:

    - name: Checkout Container
      uses: actions/checkout@v2
      with:
        path: Container
        fetch-depth: 0

    - name: Checkout Tests
      uses: actions/checkout@v2
      with:
        repository: 'unitycontainer/specification-tests'
        path: SpecificationTests

    - name: Install DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.300'

    # dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True Container\tests\Specification\Optimized
    # dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True Container\tests\Specification\Diagnostic

    # dotnet test Container\tests\Specification\Optimized
    # dotnet test Container\tests\Specification\Diagnostic
    - name: Build
      run: | 
        dotnet nuget add source "https://nuget.pkg.github.com/unitycontainer/index.json" -n github -u unitycontainer -p ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text
        dotnet remove ${{ env.containerProject }} reference "..\..\Abstractions\src\Unity.Abstractions.csproj"
        dotnet add    ${{ env.containerProject }} package Unity.Abstractions --version *-alpha*
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True ${{ env.containerProject }}
        dotnet msbuild -property:Configuration=Release -verbosity:m -restore:True Container\tests\Unity.Tests
    - name: Test
      run: | 
        dotnet test Container\tests\Unity.Tests

    - name: Publish Local Package
      run: |
        dotnet nuget push '${{ env.PackageOutputPath }}\*' --skip-duplicate --source github
